-- 1) 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE;

-- 2) 동명 동물 수 찾기
SELECT NAME, COUNT(NAME) FROM ANIMAL_INS 
WHERE NAME IS NOT NULL 
GROUP BY NAME 
HAVING COUNT(NAME) > 1
ORDER BY NAME;

-- 3) 입양 시각 구하기(1)
SELECT HOUR(DATETIME), COUNT(DATETIME) FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) <= 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME);

-- 4) 입양 시각 구하기(2)
-- 쿼리문에서 로컬 변수를 활용하는 문제
SET @HOUR = -1;
SELECT (@HOUR := @HOUR + 1) as HOUR, 
(SELECT COUNT(DATETIME) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @HOUR) as COUNT 
FROM ANIMAL_OUTS
WHERE @HOUR < 23; 
-- WHERE @hour < 23일 때까지, @hour 값이 계속 + 1씩 증가